# Generated by Django 5.2.8 on 2025-12-10 03:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream_url', models.URLField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg_occupancy', models.FloatField()),
                ('peak_occupancy', models.IntegerField()),
                ('total_detections', models.IntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.camera')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_count', models.IntegerField()),
                ('chair_count', models.IntegerField()),
                ('occupancy_rate', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.camera')),
            ],
            options={
                'indexes': [models.Index(fields=['camera', 'timestamp'], name='detection_d_camera__b0f390_idx'), models.Index(fields=['timestamp'], name='detection_d_timesta_ad2722_idx')],
            },
        ),
    ]
